version: "2"
run:
  concurrency: 4
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unconvert
    - unused
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - fmt:.*,io/ioutil:^Read.*,io:Close
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: S(1002|1008|1021)
      - linters:
          - staticcheck
        text: 'SA(1006|1019|4006|4010|4017|5007|6005|9004):'
      - linters:
          - lll
        source: '^//go:generate '
    paths:
      - .*\.hcl2spec\.go$
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - .*\.hcl2spec\.go$
      - third_party$
      - builtin$
      - examples$
